application: 'penaliche-1160'
runtime: java8
version: 'alpha-001'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: /.*
  script: unused
  login: optional
  secure: optional
